### ISSUE TITLE
Black screen bios still exists

### ISSUE THREAD

**Issue by zonetvs** [MohammadtaghiFarkhondekar/macOS-Mojave-For-Asus-ROG-GL553VD#33]
I still get the black screen when entering bios.
Is there any way to fix it

**Comment by iSWORD** [comment]
Same here. I wanted to remove the CMOS battery but it turned out to be behind the motherboard and I don't have the time to go this deep.

Does anyone know of another way to reset the BIOS without removing the battery? Does flashing a new BIOS from Windows help?

**Comment by MohammadtaghiFarkhondekar** [comment]
Hi . I will recovered video for it ( next week) . It doesn't need to remove battery ! Now clover v 11 is ok but clover v10 made bios black screen .

**Comment by zonetvs** [comment]
> Hi . I will recovered video for it ( next week) . It doesn't need to remove battery ! Now clover v 11 is ok but clover v10 made bios black screen .


Thank you very much!

**Comment by iSWORD** [comment]
> Hi . I will recovered video for it ( next week) . It doesn't need to remove battery ! Now clover v 11 is ok but clover v10 made bios black screen .

Any update on this? Thank you so much 

It doesn’t have to be a video.

**Comment by dancarvajalc** [comment]
Yeah, i wonder the same

**Comment by shivaluma** [comment]
U guys can use the AFUWIN to reflash the NVRAM of BIOS,
first download and open the AFUWIN, then download the bios file of gl553vd in asus driver website
Then open the bios file and only tick nvram in flash
after flash u can restart and the bios working again

**Comment by iSWORD** [comment]
@shivaluma thank you for the quick response.

I'm trying to download it from a trusted source though. Do you know which one it is on this page? https://ami.com/en/products/firmware-tools-and-utilities/bios-uefi-utilities/

**Comment by shivaluma** [comment]
you can download it from here
https://github.com/MohammadtaghiFarkhondekar/macOS-Mojave-For-Asus-ROG-GL553VD/issues/24
Then open AMIBIOS - AFUWIN - 64 from Windows

**Comment by iSWORD** [comment]
@shivaluma thank you. I know about that link, but I can't trust the website, and I only download from trusted source on Windows. Do you know what kind of BIOS we have in the GL553VD?

**Comment by shivaluma** [comment]
https://www.asus.com/vn/Laptops/ROG-GL553VD/HelpDesk_BIOS/
download the latest version (308)

**Comment by iSWORD** [comment]
@shivaluma thank you so much

**Comment by dancarvajalc** [comment]
Hi, I just pseudofix it.  With the program recommended from shivaluma, my Asus got blue screen when I opened it, so I had to use the program from "Aptio\afuwin\64\AfuWin64\AFUWINGUI.exe" (recommended from valinor61 from another issue). I clicked in open, show all files, select the bios file, and the second tab, the program should to be selected the flash rom, something like that, untick it and then tick the option that say "NVRAM" and next, flash. I finally could get access to bios and fix some things (I could boot my pc without a pendrive, very very weird).

Now when I boot to the hackintosh, again I can't boot to bios, so i have to do the previous process again...any ideas?

**Comment by shivaluma** [comment]
change your clover to V11 of mohammad and then reflash the nvram again

**Comment by MohammadtaghiFarkhondekar** [comment]
Next week I will send V12 + Guide .

**Comment by shivaluma** [comment]
does v12 ready sir

**Comment by MohammadtaghiFarkhondekar** [comment]
yes . updating ...
